go:
  server:
    port: 8080
    context-path: "/api"
  session:
    lifetime:
      unit: "hour"
      value: 24
  database:
    username: "root"
    password: "password"
    hostname: "localhost"
    port: 3306
    dbname: "development"